package com.github.txuritan.mental.core.common.coremod

import com.github.txuritan.mental.core.common.util.References
import com.google.common.eventbus.EventBus
import net.minecraftforge.fml.common.DummyModContainer
import net.minecraftforge.fml.common.LoadController
import net.minecraftforge.fml.common.Mod
import net.minecraftforge.fml.common.ModMetadata
import net.minecraftforge.fml.common.event.FMLInitializationEvent
import net.minecraftforge.fml.relauncher.FMLRelaunchLog

class ModContainerMental : DummyModContainer() {
    private val modMetadata = ModMetadata()

    init {
        FMLRelaunchLog.info("[Mental] Core Init")
        this.modMetadata.autogenerated = false
        this.modMetadata.authorList.add("Ian \"Txuritan\" Cronkright")
        this.modMetadata.credits = "No one as of yet"
        this.modMetadata.modId = this.modId
        this.modMetadata.version = this.version
        this.modMetadata.name = this.name
        this.modMetadata.url = "https://txuritan.github.io/mental/"
        this.modMetadata.description = "Core mod for Mental"
    }

    @Mod.EventHandler
    fun load(event: FMLInitializationEvent) {

    }

    override fun getMetadata(): ModMetadata {
        return this.modMetadata
    }

    override fun getModId(): String {
        return "mental-core"
    }

    override fun getName(): String {
        return "Mental Core"
    }

    override fun getVersion(): String {
        return References.VERSION
    }

    override fun registerBus(bus: EventBus?, controller: LoadController?): Boolean {
        bus?.register(this)
        return true
    }

    override fun getDisplayVersion(): String {
        return this.version
    }
}
